GET http://localhost:3000/products
Content-Type: "application/json"

### Create product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "image_url": "https://via.placeholder.com/150"
}

### Get products
GET http://localhost:3000/products
### Get product by id
GET http://localhost:3000/products/1