GET http://localhost:3000/products
Content-Type: "application/json"


### Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "john123"
}

###
@authToken = {{login.response.body.access_token}}

### Create order
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}
 
{
  "items": [
    {
      "product_id": "5b1f0513-06b5-439b-909b-e1bb46d03e1b",
      "quantity": 1
    },
    {
      "product_id": "e55400c2-4bfc-4cf9-9ce5-4787a27c5711",
      "quantity": 2
    }
  ],
  "card_hash": "456"
}

### Get orders
GET http://localhost:3000/orders
Authorization: Bearer {{authToken}}

### Get order bt id
GET http://localhost:3000/orders/10e8c662-1318-4af5-94b0-cea991b66e6a
Authorization: Bearer {{authToken}}


### Create product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "image_url": "https://via.placeholder.com/150"
}

### Get products
GET http://localhost:3000/products

### Get product by id
GET http://localhost:3000/products/1