version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: nestjs-api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
 
 rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin